"""Risk classifier - Part 1, Activity A10b.

PyTorch ANN that predicts HIGH/MEDIUM/LOW risk tier from a SMILES string.
Run this file directly to train + save. Import RiskClassifier elsewhere
to load + predict.

What this model does: maps 16 molecular features (similarity, drug-likeness,
structural alerts, scaffold overlap, etc.) to a 3-class risk tier with
calibrated probabilities, so downstream code can sort or threshold candidates.

Training data: MolGPT-generated v2 molecules only (v2_validated.csv +
v2_T08_validated.csv), canonicalized and de-duplicated, with any SMILES
that overlaps MolGPT's own training set removed to avoid memorization leakage.

Labels: temporary weak labels generated by the rule-based weak_label()
function below (structural alerts + Lipinski violations + QED + warhead
presence). These are placeholders; the ANN is learning to generalize the
rule, not predict any real-world ground truth.

Why ML on top of the weak_label rule:
1. Outputs probabilities (for example: LOW=0.51 vs LOW=0.99) instead of a hard tier.
2. Learns non-linear feature interactions the rule's hard thresholds cannot.

Developed with AI assistance for syntax support.
"""
import sys
from pathlib import Path
from dataclasses import dataclass, field

import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.preprocessing import StandardScaler
from rdkit import Chem


_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from Compund_Matching_Engine.compound_loader import CompoundLoader
from Compund_Matching_Engine.fingerprint_encoder import FingerprintEncoder
from Compund_Matching_Engine.Similarity_scorer import SimilarityScorer
from Compund_Matching_Engine.Drug_likeness_filter import DrugLikenessFilter
from Compund_Matching_Engine.Scaffold_extractor import ScaffoldExtractor


TIERS = ("HIGH", "MEDIUM", "LOW")
FEATURES = [
    "tanimoto", "potency_score", "pains_flag", "brenk_flag",
    "lipinski_violations", "qed", "mw", "logp", "hbd", "hba",
    "tpsa", "rot_bonds", "scaffold_similarity", "shared_pct",
    "novel_atoms", "composite_risk",
]
MODEL_PATH = Path(__file__).resolve().parent / "risk_classifier_ann.pt"


def featurize(row_or_smiles, helpers: dict) -> dict | None:
    """SMILES str OR row dict -> dict with all 16 features. Returns None if
    the SMILES cannot be parsed. Extra columns from a CSV row (for example:
    warhead_match, lipinski_pass) are preserved so weak_label can use them."""
    row = {"smiles": row_or_smiles} if isinstance(row_or_smiles, str) else dict(row_or_smiles)
    mol = Chem.MolFromSmiles((row.get("smiles") or "").strip())
    if mol is None:
        return None

    row.update(helpers["filter"].filter(mol).to_ml_features())
    try:
        sim = helpers["scorer"].score(helpers["encoder"].encode(mol))
        row["tanimoto"] = float(sim.nn_score)
        row["potency_score"] = round(1.0 / (1.0 + (sim.nn_ic50 or 0) / 100.0), 4) if sim.nn_ic50 else 0.0
        nn_mol = Chem.MolFromSmiles(sim.nn_smiles or "")
        if nn_mol:
            sc = helpers["scaffold"].extract(mol, nn_mol)
            row["scaffold_similarity"] = float(sc.scaffold_similarity)
            row["shared_pct"] = float(sc.shared_pct)
            row["novel_atoms"] = float(sc.novel_atoms)
    except Exception as e:
        print(f"[A10b] similarity failed for {row['smiles'][:40]}: {e}")

    lipinski_violations = float(row.get("violations") or 0)
    row["lipinski_violations"] = lipinski_violations
    # Composite drug-likeness penalty: weighted sum of structural alert,
    # rule-of-five, and property-range red flags (derived from existing flags,
    # not from any external assay/clinical data).
    row["composite_risk"] = round(min(
        0.35 * bool(row.get("pains_flag")) + 0.25 * bool(row.get("brenk_flag"))
        + 0.25 * (lipinski_violations >= 2) + 0.15 * (0 < float(row.get("qed", 0)) < 0.34)
        + 0.10 * (float(row.get("logp", 0)) > 5.5) + 0.10 * (float(row.get("mw", 0)) > 600),
        1.0
    ), 4)
    return row


@dataclass
class RiskPrediction:
    tier: str
    proba: dict = field(default_factory=dict)
    confidence: float = 0.0


class RiskClassifier:
    """Wraps a trained ANN for HIGH/MEDIUM/LOW prediction."""

    def __init__(self, model, scaler):
        self.model = model
        self.scaler = scaler  # sklearn StandardScaler fit on training data
        self.helpers = None

    def predict(self, smiles) -> RiskPrediction:
        # Accept either a SMILES string or a MatchResult-like object that
        # exposes .query_smiles, so callers from MatchingEngine work directly.
        if hasattr(smiles, "query_smiles"):
            smiles = smiles.query_smiles
        if self.helpers is None:
            self.helpers = {
                "encoder": FingerprintEncoder(), "filter": DrugLikenessFilter(),
                "scaffold": ScaffoldExtractor(),
                "scorer": SimilarityScorer(CompoundLoader().load_reference_library()),
            }
        row = featurize(smiles, self.helpers) or {}
        x_raw = [[float(row.get(f, 0)) for f in FEATURES]]
        x = torch.from_numpy(self.scaler.transform(x_raw)).float()

        self.model.eval()
        with torch.no_grad():
            probs = torch.softmax(self.model(x), dim=-1).squeeze(0)
        proba = {t: round(probs[i].item(), 4) for i, t in enumerate(TIERS)}
        tier = max(proba, key=proba.get)
        return RiskPrediction(tier=tier, proba=proba, confidence=proba[tier])

    @classmethod
    def load(cls, path=MODEL_PATH):
        saved = torch.load(path, weights_only=False)
        # Schema check: refuse to load if the saved feature order or tier
        # order no longer matches the current source. Silent mismatch would
        # feed wrong values into the model and produce plausible-looking junk.
        if saved.get("features") != list(FEATURES) or saved.get("tiers") != list(TIERS):
            raise ValueError(
                f"Schema mismatch in {path.name}. "
                f"saved features={saved.get('features')} tiers={saved.get('tiers')} "
                f"vs current FEATURES={FEATURES} TIERS={TIERS}. Retrain to fix."
            )
        return cls(saved["model"], saved["scaler"])


if __name__ == "__main__":
    def weak_label(row):
        """Rule-based HIGH/MEDIUM/LOW label, used as temporary training target.
        Extended variant of A10a's assign_rule_tier (matching_engine.py): same
        PAINS / Brenk / violations triggers, plus a warhead_match check; LOW
        requires lipinski_pass + QED + tanimoto thresholds combined."""
        lipinski_violations = float(row.get("violations") or 0)
        if (row.get("pains_flag") or row.get("brenk_flag")
                or lipinski_violations >= 2
                or ("warhead_match" in row and not row["warhead_match"])):
            return "HIGH"
        if (row.get("lipinski_pass") and float(row.get("qed", 0)) >= 0.34
                and float(row.get("tanimoto", 0)) >= 0.45):
            return "LOW"
        return "MEDIUM"

    def canon(s):
        """RDKit canonical SMILES so 'CC(C)c1c(...)' and 'CC(C)c1nc(...)' for the
        same molecule collapse to one string. None for invalid SMILES."""
        m = Chem.MolFromSmiles((s or "").strip())
        return Chem.MolToSmiles(m) if m else None

    DATA_DIR = Path(__file__).resolve().parents[1]
    read_csv = lambda p: pd.read_csv(p, true_values=["True"], false_values=["False"])

    # Load v2 generated molecules, canonicalize, dedup.
    df = (pd.concat([read_csv(p) for p in
                     [DATA_DIR / "generation_run" / "v2_validated.csv",
                      DATA_DIR / "generation_run" / "v2_T08_validated.csv"]])
            .dropna(subset=["smiles"])
            .assign(canon=lambda d: d["smiles"].map(canon))
            .dropna(subset=["canon"])
            .drop_duplicates(subset="canon"))

    # Drop molecules MolGPT just memorized from its training set (circularity).
    memorized = {canon(s) for p in [DATA_DIR / "EDA" / "MolGPT" / "statin.csv",
                                    DATA_DIR / "datasets" / "statin_augmented.csv"]
                 for s in read_csv(p)["smiles"].dropna()} - {None}
    n_before = len(df)
    df = df[~df["canon"].isin(memorized)]
    print(f"v2 canonical unique: {n_before} -> after memorization filter: {len(df)} "
          f"(dropped {n_before - len(df)} memorized)")

    # Heavy step: RDKit per molecule. Build a feature DataFrame so weak_label
    # and X/y extraction are one-liners below.
    helpers = {"encoder": FingerprintEncoder(), "filter": DrugLikenessFilter(),
               "scaffold": ScaffoldExtractor(),
               "scorer": SimilarityScorer(CompoundLoader().load_reference_library())}
    features_df = pd.DataFrame(filter(None, (featurize(r, helpers) for r in df.to_dict("records"))))

    # Assign each molecule a temporary HIGH/MEDIUM/LOW label via the rule-based
    # weak_label() (placeholder until real ground-truth labels are available).
    features_df["tier"] = features_df.apply(weak_label, axis=1)
    print(f"loaded {len(features_df)} rows, label_counts={features_df['tier'].value_counts().to_dict()}")

    # reindex(columns=FEATURES) enforces the exact 16-feature order and fills any missing column.
    X = torch.tensor(features_df.reindex(columns=FEATURES, fill_value=0).astype(float).values,
                     dtype=torch.float32)
    y = torch.tensor(features_df["tier"].map(TIERS.index).values, dtype=torch.long)

    def train_one(X_train, y_train, val_data=None, max_epochs=500, patience=30,
                  min_epochs=50, seed=42, verbose=False):
        """Train one ANN on (X_train, y_train). Returns (model, scaler, best_epoch).
        Reused for every CV fold and the final whole-data model so the
        training procedure is guaranteed identical across runs.

        val_data: optional (X_val, y_val). When given, enables EARLY STOPPING:
        training halts if val_acc has not improved for `patience` epochs, and
        the model is restored to the weights that achieved the best val_acc.
        Without val_data, runs the full max_epochs (no stopping criterion)."""
        scaler = StandardScaler()
        X_scaled = torch.from_numpy(scaler.fit_transform(X_train.numpy())).float()
        X_val_scaled = None
        if val_data is not None:
            X_val, y_val = val_data
            X_val_scaled = torch.from_numpy(scaler.transform(X_val.numpy())).float()
        # class weights from this fold's train labels only (no leakage).
        counts = torch.bincount(y_train, minlength=3).float()
        weights = counts.sum() / (counts * 3)
        torch.manual_seed(seed)
        model = nn.Sequential(
            nn.Linear(16, 64), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(64, 32), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(32, 3),
        )
        optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
        loss_fn = nn.CrossEntropyLoss(weight=weights)
        loader = DataLoader(TensorDataset(X_scaled, y_train), batch_size=64, shuffle=True)

        best_val_acc = 0.0
        best_state = None
        best_epoch = max_epochs  # fallback if no val_data / no improvement
        epochs_no_improve = 0

        for epoch in range(1, max_epochs + 1):
            model.train()
            epoch_loss = 0.0
            for batch_x, batch_y in loader:
                optimizer.zero_grad()
                batch_loss = loss_fn(model(batch_x), batch_y)
                batch_loss.backward()
                optimizer.step()
                epoch_loss += batch_loss.item()

            # Track best val_acc each epoch for early stopping.
            if X_val_scaled is not None:
                model.eval()
                with torch.no_grad():
                    val_acc = (model(X_val_scaled).argmax(-1) == y_val).float().mean().item()
                if val_acc > best_val_acc:
                    best_val_acc = val_acc
                    best_state = {k: v.clone() for k, v in model.state_dict().items()}
                    best_epoch = epoch
                    epochs_no_improve = 0
                else:
                    epochs_no_improve += 1

            if verbose and epoch % 40 == 0:
                avg_loss = epoch_loss / len(loader)
                model.eval()
                with torch.no_grad():
                    train_acc = (model(X_scaled).argmax(-1) == y_train).float().mean().item()
                    if X_val_scaled is not None:
                        print(f"  epoch {epoch:>3} | loss={avg_loss:.4f}  "
                              f"train_acc={train_acc:.3f}  val_acc={val_acc:.3f}")
                    else:
                        print(f"  epoch {epoch:>3} | loss={avg_loss:.4f}  train_acc={train_acc:.3f}")

            # Early stop: val_acc hasn't improved for `patience` epochs.
            # Skip the noisy early phase (acc on imbalanced data spikes randomly).
            if (X_val_scaled is not None and epoch >= min_epochs
                    and epochs_no_improve >= patience):
                if verbose:
                    print(f"  early stop at epoch {epoch}  "
                          f"(best val_acc={best_val_acc:.3f} at epoch {best_epoch})")
                break

        # Restore best weights so the returned model is the best-val one.
        if best_state is not None:
            model.load_state_dict(best_state)
        return model, scaler, best_epoch

    # --- Hold out 20% as a true unseen test set BEFORE any training ---
    # Test set never appears in CV folds or final model training.
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y,
    )
    print(f"\ntrain: {len(y_train)}  held-out test: {len(y_test)}")

    # --- 5-fold stratified CV on the train portion (robustness assessment) ---
    # Each fold uses early stopping; we record the best-val epoch per fold and
    # use the median to size the final model's training run.
    print("\n--- 5-fold stratified CV (on train portion only) ---")
    cv_accuracies = []
    cv_best_epochs = []
    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    for cv_step, (cv_train_idx, cv_val_idx) in enumerate(kfold.split(X_train, y_train), 1):
        cv_model, cv_scaler, best_epoch = train_one(
            X_train[cv_train_idx], y_train[cv_train_idx],
            val_data=(X_train[cv_val_idx], y_train[cv_val_idx]),
        )
        X_val = torch.from_numpy(cv_scaler.transform(X_train[cv_val_idx].numpy())).float()
        cv_model.eval()
        with torch.no_grad():
            predictions = cv_model(X_val).argmax(-1)
        accuracy = (predictions == y_train[cv_val_idx]).float().mean().item()
        cv_accuracies.append(accuracy)
        cv_best_epochs.append(best_epoch)
        print(f"  cv step {cv_step}: val_acc = {accuracy:.3f}  (best epoch = {best_epoch})")

    accuracies = pd.Series(cv_accuracies)
    print(f"\nmean cv val_acc = {accuracies.mean():.3f}")

    # --- Final model: train on full 80% train, evaluate ONCE on held-out test ---
    # Use the median best-epoch from CV folds: this is the data-driven sweet
    # spot before overfitting kicks in. No val_data here so it just runs that
    # many epochs (early stopping isn't applicable without a val set).
    final_epochs = int(pd.Series(cv_best_epochs).median())
    print(f"\n--- training final model on {len(y_train)} samples "
          f"(epochs={final_epochs}, median of CV best epochs {cv_best_epochs}) ---")
    model, scaler, _ = train_one(X_train, y_train, max_epochs=final_epochs, verbose=True)

    X_test_scaled = torch.from_numpy(scaler.transform(X_test.numpy())).float()
    model.eval()
    with torch.no_grad():
        test_predictions = model(X_test_scaled).argmax(-1)
    test_accuracy = (test_predictions == y_test).float().mean().item()
    test_confusion = pd.crosstab(
        pd.Series([TIERS[i] for i in y_test.tolist()], name="true"),
        pd.Series([TIERS[i] for i in test_predictions.tolist()], name="pred"),
    )
    print(f"\nFINAL test_acc = {test_accuracy:.3f}  (on {len(y_test)} held-out molecules)")
    print(test_confusion)

    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {"model": model, "scaler": scaler, "features": list(FEATURES), "tiers": list(TIERS)},
        MODEL_PATH,
    )
    print(f"\nsaved -> {MODEL_PATH}")

    demo = "CC(=O)c1c(F)c(-c2ccc(F)cc2)c(-c2ccc(F)cc2)n1CCC(O)CC(O)CC(=O)O"
    print(RiskClassifier.load().predict(demo))
