name: project_env
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pyg
  - torch-geometric
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - pytorch-spline-conv
  - rdkit
  - pandas
  - numpy
  - requests

  - pip:
      - stringdb