name: project_env

channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn=1.7.2
  - pytorch
  - torchvision
  - torchaudio
  - pyg
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - pytorch-spline-conv
  - networkx
  - transformers=4.41.0
  - rdkit
  - biopython
  - goatools
  - requests
  - rich
  - pip
  
  - pip:
      - node2vec
      - stringdb