from dataclasses import dataclass, field

@dataclass
class RiskScore:
    """Final pipeline output container for one AI-generated compound.

    Aggregates evidence from all three pipeline stages:
      - Part 1  Compound Matching  -> similarity_score
      - Part 2A NLP Literature     -> literature_risk_score
      - Part 2B PPI / GNN Network  -> network_risk_score

    Attributes
    ----------
    risk_tier : str
        Part 3 final HIGH/MEDIUM/LOW classification from EvidenceAggregator.

    similarity_score : float
        Part 1 raw A5 Tanimoto similarity from MatchResult.

    literature_risk_score : float
        Part 2A NLP-derived literature risk score from LiteratureResult.

    network_risk_score : float
        Part 2B PPI/GNN-derived network risk score.

    combined_score : float
        Part 3 weighted combination of Part 1, Part 2A, and Part 2B risk signals.

    flagged_proteins : list[str]
        Part 2B proteins flagged during PPI/GNN network analysis.

    top_signals : list[dict]
        Part 2A highest-confidence literature signals from LiteratureResult.

    ml_proba : dict
        Part 1 A10b ANN softmax probabilities before A10c rule-vs-ML reconciliation.

    target : str
        Part 1 target protein context from `MatchResult`, shared across Part 2A and Part 2B.

    search_terms : str
        Part 1 PubMed query terms generated by `MatchingEngine` and used by the NLP agent.

    confidence_flag : str
        Part 1 A10c rule-vs-ML agreement flag from `MatchingEngine`.

    evidence_level : str
        Part 2A evidence strength level from `LiteratureResult`.

    pmids : list[str]
        Part 2A supporting PubMed IDs from `LiteratureResult`.
    """

    # Final HIGH/MEDIUM/LOW classification based on combined_score and stream agreement.
    risk_tier: str = ""
    similarity_score: float = 0.0
    literature_risk_score: float = 0.0
    network_risk_score: float = 0.0
    # Weighted aggregation of similarity, literature, and network evidence streams.
    combined_score: float = 0.0

    # Proteins flagged by Part 2B and attached by EvidenceAggregator.
    # Currently populated through the temporary Part 2B input helper; later from NetworkResult.
    flagged_proteins: list[str] = field(default_factory=list)
    top_signals: list[dict] = field(default_factory=list)
    ml_proba: dict = field(default_factory=dict)

    target: str = "HMGCR"
    search_terms: str = ""
    confidence_flag: str = ""
    evidence_level: str = ""
    pmids: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Return a plain dict for reporting, JSON export, or notebooks."""
        return {
            "risk_tier": self.risk_tier,
            "similarity_score": round(self.similarity_score, 4),
            "literature_risk_score": round(self.literature_risk_score, 4),
            "network_risk_score": round(self.network_risk_score, 4),
            "combined_score": round(self.combined_score, 4),
            "flagged_proteins": self.flagged_proteins,
            "top_signals": self.top_signals,
            "ml_proba": self.ml_proba,
            "target": self.target,
            "search_terms": self.search_terms,
            "confidence_flag": self.confidence_flag,
            "evidence_level": self.evidence_level,
            "pmids": self.pmids,
        }

    def __repr__(self) -> str:
        return (
            f"RiskScore(tier={self.risk_tier!r}, combined={self.combined_score:.3f}, "
            f"similarity={self.similarity_score:.3f}, literature={self.literature_risk_score:.3f}, "
            f"network={self.network_risk_score:.3f})"
        )